name: wallet
description: flutter lib for managing crypto keys
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/wallet
issue_tracker: https://github.com/tiki/wallet/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  pointycastle: ^3.5.0
  flutter_secure_storage: ^5.0.2
  httpp:
    path: ../httpp

dev_dependencies:
  flutter_test:
    sdk: flutter